from tkinter import *
from tkinter.filedialog import askopenfilename
root = Tk()
root.geometry('400x200')
menu = Menu(root)
root.config(menu=menu)
filemenu = Menu(menu)
menu.add_cascade(label="File", menu=filemenu)
filemenu.add_command(label="New")
filemenu.add_command(label="new window...")
filemenu.add_command(label="open")
filemenu.add_command(label="Save")
filemenu.add_command(label="Save as...")
filemenu.add_separator()

filemenu.add_command(label="Exit")
editmenu=Menu(menu)
menu.add_cascade(label="edit", menu=editmenu)
editmenu.add_command(label="undo")
editmenu.add_command(label="cut")
editmenu.add_command(label="copy")
editmenu.add_command(label="past")
editmenu.add_command(label="Delet")
editmenu.add_command(label="search with Bing... ")
editmenu.add_command(label="Find...")
editmenu.add_command(label="Find Next")
editmenu.add_command(label="Find previous")
editmenu.add_command(label="Replace")
editmenu.add_command(label="Go to...")
editmenu.add_command(label="Select All")
editmenu.add_command(label="Time/Date")

Formetmenu=Menu(menu)
menu.add_cascade(label="Formet", menu=Formetmenu)
Formetmenu.add_command(label="Word Warp")
Formetmenu.add_command(label="Font...")

Viewmenu=Menu(menu)
menu.add_cascade(label="View", menu=Viewmenu)
Viewmenu.add_command(label="Zoom")
Viewmenu.add_command(label="Status Bar")

Helpmenu=Menu(menu)
menu.add_cascade(label="Help", menu=Helpmenu)
Helpmenu.add_command(label="View Help")
Helpmenu.add_command(label="Send Feedback")

# Friendsmenu=Menu(menu)
# menu.add_cascade(label="Friends", menu= Friendsmenu)
# Friendsmenu.add_command(label="vignesh")
# Friendsmenu.add_command(label="Gopinath")
# Friendsmenu.add_command(label="Nirmal")
# Friendsmenu.add_command(label="Prasanth")
# Friendsmenu.add_command(label="Nishanth")
# Friendsmenu.add_command(label="Dharun")

root.mainloop()
